osx_image: xcode7.2
language: objective-c

cache:
  - cocoapods
before_install:
  - brew install xctool
  - gem install cocoapods -v 0.39.0
  - pod install
  
script: 
  - xctool -workspace CKToolbox.xcworkspace -scheme TableViewDemo -sdk iphonesimulator build
  - xctool -workspace CKToolbox.xcworkspace -scheme Tests -sdk iphonesimulator test
  