osx_image: xcode7.3
language: objective-c

cache:
  - cocoapods
rvm:
  - 2.2.4
before_install:
  - brew install xctool
  - gem install cocoapods -v "1.0.1"
  - pod install
script: 
  - xctool -workspace CKToolbox.xcworkspace -scheme TableViewDemo -sdk iphonesimulator build
  - xctool -workspace CKToolbox.xcworkspace -scheme Tests -sdk iphonesimulator test
  